[layers.hardwareDeps]
modules = [
    "com.pi4j:pi4j-core:1.2",
    "com.pi4j:pi4j-device:1.2",
    "com.pi4j:pi4j-gpio-extension:1.2"]
[layers.app]
parents = ["hardwareDeps"]
modules = ["com.gmail.pzalejko.weather:core:1.0-SNAPSHOT"]
[main]
module = "pzalejko.weatchersensor"
class = "com.gmail.pzalejko.weather.core.CoreLauncher"